import type { Metadata } from "next";
import "./globals.css";
import Background from "@/components/layout/background";
import Header from "@/components/layout/header/header";

export const metadata: Metadata = {
  title: "Aidan Holton | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body>
        <Header />
        {children}
        <Background />
      </body>
    </html>
  );
}
